FROM node:latest
WORKDIR /usr/src/app

# Backend setup
COPY backend/package*.json ./backend/
RUN cd backend && npm install

# Frontend setup
COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install

# Esponi la porta 8000 invece di 3000
EXPOSE 8000

# Avvio del container con NODE_ENV=production
CMD sh -c "cd /usr/src/app/frontend && NODE_ENV=production npm run build && cd /usr/src/app/backend && node index.js"