# Usa un'immagine Node.js come base
FROM node:14

# Crea e imposta la directory di lavoro nel contenitore
WORKDIR /usr/src/app

# Copia il file package.json e package-lock.json nella directory di lavoro
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il codice sorgente nella directory di lavoro
COPY . .

# Esponi la porta 3000 (o la porta che stai utilizzando nel tuo server)
EXPOSE 3000

# Avvia il tuo server quando il contenitore viene eseguito
CMD ["node", "index.js"]