FROM node:latest

WORKDIR /usr/src/app

# Backend setup
COPY backend/package*.json ./backend/
RUN cd backend && npm install

# Frontend setup
COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install

EXPOSE 3000

# Avvio del container
CMD sh -c "cd /usr/src/app/frontend && npm run build && cd /usr/src/app/backend && node index.js"
