services:
  mongo:
    image: mongo:latest
    container_name: selfie-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./data/db:/data/db  
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_DATABASE: selfie-db
    depends_on:
      - mongo
    volumes:
      - ./data/mongo-express:/data 
    restart: unless-stopped
    
  node-server:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: node-server
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      MONGODB_URI: ${MONGODB_URI}